### PR TITLE
Upgrade to v1.3

### PR DESCRIPTION
**Pull request by jlev**
Hey Cayden, some new features in [version 1.3](https://github.com/spacedogXYZ/call-power/releases/tag/v1.3.0).

Let me know if you have any questions about merging, or new features you'd like to add.

- Josh

### CODE REVIEW

**Comment by catachresis** [comment]
Trying to get a staging app up on Heroku and when I try to migrate up the database it poops out some errors. Not familiar enough with Flask & Alembic to figure out what's going on here:

heroku

**Comment by jlev** [comment]
Weird. I did just find an issue with deploying a new instance, and pushed that in 9693c298ffdb5f049ea52ac83f6b6621c012d9f1. The gevent database module I was using got deprecated while I wasn't looking, so wouldn't install from pip.

**Comment by jlev** [comment]
Also, you may want to obfuscate that screenshot, because it's got your database credentials in it... Or rotate them via the Heroku Postgres dashboard.

**Comment by catachresis** [comment]
There is no grimace face emoji react.

**Pull request merged**
